name: A workflow to build an application

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    name: Build the app
    runs-on: windows-latest
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c release --no-restore
    
    tests:
      name: Unit Testing
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2.1.0
        - run: dotnet test